config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'sessions/new'
  
  resources :users
  resources :items
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :testsessions, only: :create
  
  get 'likes/index'
  post '/likes', to: 'likes#create'
  delete '/likes', to: 'likes#destroy'
  
  get 'comments/new'
  post '/comments', to: 'comments#create'
  
  get "items/:id/edit" => "items#edit"
  post "items/:id/update" => "items#update"
  post "items/:id/destroy" => "items#destroy"
  
  
   
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 30 }
  
  belongs_to :user
  belongs_to :item
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/item.rb
class Item < ApplicationRecord
  validates :user_id, :product, :description, :image, presence: true
  validates :product, length: { maximum: 30 }
  validates :price, numericality: true
  validates :price, length: { maximum: 8 }
  validates :description, length: { maximum: 500 }
  
  belongs_to :user
  has_many :likes
  has_many :like_users, through: :likes, source: 'user'
  has_many :comments
  
  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 100 }
  
  belongs_to :user
  belongs_to :room
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :from, :email,presence: true
  validates :name, length: { maximum: 15 }
  validates :age, numericality: true
  validates :age, length: { maximum: 2 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8, maximum: 32 }
  validates :password, format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]+\z/ }
  
  has_secure_password
  
  has_many :items
  has_many :likes
  has_many :like_items, through: :likes, source: 'item'
  has_many :comments
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @search = Item.search(params[:q])
    @items = @search.result.page(params[:page]).per(6)
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path, success: '商品を投稿しました'
    else
      flash.now[:danger] = "商品の投稿に失敗しました"
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = current_user.items.find(params[:id])
  end
  
  def update
    @item = current_user.items.find(params[:id]) 
    @item.update(item_params)
    redirect_to root_path, success: '投稿を編集しました'
  end
    
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    redirect_to root_path, success: '投稿を削除しました'
  end
  
  private
  def item_params
    params.require(:item).permit(:image, :product, :price, :description)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end  
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        redirect_to root_path, success: 'ユーザー情報を編集しました'
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました'
        render :edit
      end
    else
      redirect_to root_url
    end
  end

  

  
  def index
    @user_items = current_user.items
  end
  
  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end  
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :age, :from, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testsessions_helper.rb
module TestsessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">ユーザー情報変更画面</h1>
        <%= form_for @user do |f| %>
        
        <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group">
            <%= f.label :name, '名前 ※最大15文字', class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :age, '年齢 ※数字を入力', class: 'text-white' %>
            <%= f.number_field :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :from, '都道府県:', class: 'text-white' %>
            <%= f.collection_select :from, Prefecture.all, :name, :name %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス', class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password, 'パスワード ※8文字以上', class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード再確認', class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <% if current_user != User.find_by(email:"test@example.com")%>
            <% if current_user.id == @user.id %>
              <%= f.submit "変更する", class: 'btn-block btn-white' %>
            <% end %>
          <% else %>
            <h1 class="text-white">テストログインユーザーは情報を変更することはできません。</h1>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="item-index-wrapper">
  <div class="container">
    <% if @user_items.present? %>
      <% @user_items.each do |item| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="item-index-single">
              <h2 class="item-author">
                <%= item.user.name %>
              </h2>
              <%= image_tag item.image.url %>
              <p class=item-text>
                [商品名] <%= item.product %>
              </p>
              <p class=item-text>
                [価格] <%= item.price %>円
              </p>
              <p class=item-text>
                [説明] <%= item.description %>
              </p>
              <hr>
              <h3>コメント</h3>
              <% item.comments.each do |comment| %>
                <P><%= comment.content %></P>
              <% end %>
              
              <div class="item-menus">
                <%= link_to "削除", item_path(id: item.id),{method:"delete"} %>
              </div>
              <div class="item-menus">
                <%= link_to "編集", edit_item_path(id: item.id),{method:"get"} %>
              </div>
              <div class="item-menus">
                <%= link_to "コメントする", comments_new_path(item_id: item.id), {method: :get} %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="user-like-index-container text-center">
        <h1>現在あなたの投稿はありません</h1>
        <%= link_to '投稿を作成する', new_item_path, class: 'btn btn-primary btn-primary btn-lg' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>
        <%= form_for @user do |f| %>
        
        <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group">
            <%= f.label :name, '名前 ※最大15文字', class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :age, '年齢 ※半角数字を入力', class: 'text-white' %>
            <%= f.number_field :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :from, '都道府県:', class: 'text-white' %>
            <%= f.collection_select :from, Prefecture.all, :name, :name %>
          </div>
          
          <div class="form-group">
            <%= f.label :email, 'メールアドレス', class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password, 'パスワード ※英数字混合8文字以上', class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード再確認', class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">ユーザー詳細</h1>
        <h2 class="text-center"><%= @user.name %>さんのページ</h2>
        <div class="text-center">        
          <% if @user.id == current_user.id %>
            <%= link_to "ユーザー情報の編集",edit_user_path(user_id: @user.id), {method:"get"} %>
          <% else %>
            <% if @isRoom == true %>
              <p><a class="btn btn-primary" href="/rooms/<%= @roomId %>" role="button">メッセージ画面へ</a>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, :value=> @user.id %>
                <% end %>
                <%= f.submit "メッセージを送る", class: "btn btn-primary btn-primary" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>