config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'sessions/new'
  
  resources :users
  resources :items
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :testsessions, only: :create
  
  get 'likes/index'
  post '/likes', to: 'likes#create'
  delete '/likes', to: 'likes#destroy'
  
  get 'comments/new'
  post '/comments', to: 'comments#create'
  
  get "items/:id/edit" => "items#edit"
  post "items/:id/update" => "items#update"
  post "items/:id/destroy" => "items#destroy"
  
  
   
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 30 }
  
  belongs_to :user
  belongs_to :item
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/item.rb
class Item < ApplicationRecord
  validates :user_id, :product, :description, :image, presence: true
  validates :product, length: { maximum: 30 }
  validates :price, numericality: true
  validates :price, length: { maximum: 8 }
  validates :description, length: { maximum: 500 }
  
  belongs_to :user
  has_many :likes
  has_many :like_users, through: :likes, source: 'user'
  has_many :comments
  
  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 100 }
  
  belongs_to :user
  belongs_to :room
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :from, :email,presence: true
  validates :name, length: { maximum: 15 }
  validates :age, numericality: true
  validates :age, length: { maximum: 2 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8, maximum: 32 }
  validates :password, format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]+\z/ }
  
  has_secure_password
  
  has_many :items
  has_many :likes
  has_many :like_items, through: :likes, source: 'item'
  has_many :comments
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alerts alert-danger text-center">
    <ul>
      <% model.errors.full_messages.each do |user| %>
        <li><%= user %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greatconnect</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="navbar-header">
        <%= link_to root_path do %>
          <p class="navbar-brand">GreatConnect</p> 
        <% end %>
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">メニュー</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        
        <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="gnavi" >
          <% if logged_in? %>
            <li>
              <%= link_to root_path do %>
                <%= image_tag "icon/home.png" %>
                <p>ホーム</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_item_path do %>
                <%= image_tag "icon/post.png", class: "icon1" %>
                <p>投稿する</p>
              <% end %>
            </li>
            <li>
              <%= link_to items_path do %>
                <%= image_tag "icon/list of posts.png", class: "icon1" %>
                <p>マーケット</p>
              <% end %>
            </li>
            <li>
              <%= link_to rooms_path do %>
                <%= image_tag "icon/message3.png", class: "icon1" %>
                <p>メッセージ</p>
              <% end %>
            </li>
            <li>
              <%= link_to likes_index_path do %>
                <%= image_tag "icon/favorite.png", class: "icon1" %>
                <p>お気に入り</p>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
                <%= image_tag "icon/myposts.png", class: "icon1" %>
                <p>自分の投稿</p>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <%= image_tag "icon/edit.png", class: "icon2"%>
                <p>ユーザー<br>情報変更</p>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icon/logout.png", class: "icon1" %>
                <p>ログアウト</p>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
                <%= image_tag "icon/home.png" %>
                <P>ホーム</P>
              <% end %>
            </li>
            <li>
              <%= link_to items_path do %>
                <%= image_tag "icon/list of posts.png", class: "icon1" %>
                <p>マーケット</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icon/post.png", class: "icon1" %>
                <p>新規登録</p>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icon/login.png" %>
                <p>ログイン</p>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>